name: Deploy sft contract
on:
  push:
    branches: [ main ]
    paths:
      - fc-community-contracts/src/FactchainSFT.sol
      - fc-community-contracts/src/utils/Ownable.sol
  workflow_dispatch:
jobs:
  deploy-contract:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - uses: YBadiss/deploy-contract@v1
        with:
          contract-name: 'FactchainSFT'
          parent-dir: 'fc-community-contracts'
          chain-id: '11155111'
          rpc-url: ${{ secrets.RPC_ETH_SEPOLIA_HTTPS }}
          deployer-pk: ${{ secrets.DEPLOYER_PK }}
          constructor-args: '${{ vars.NFT_OWNER_ADDRESS }}'
          verify: true
          etherscan-url: 'https://sepolia.etherscan.io'
          etherscan-api-key: ${{ secrets.ETHERSCAN_SEPOLIA_API_KEY }}
